title: Technical Foundations of Generative AI for Business
description: Course site for Technical Foundations of Generative AI for Business
theme: just-the-docs

url: https://midhubalan.github.io/gen-ai-4-business/

# Aux links for the upper right navigation
aux_links:
  "Course Repository on GitHub":
    - "//github.com/midhubalan/gen-ai-4-business"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
