title: Technical Foundations of Generative AI for Business
description: Course site for Technical Foundations of Generative AI for Business
theme: just-the-docs

url: https://midhubalan.github.io/gen-ai-4-business/

# Aux links for the upper right navigation
aux_links:
  "Course Repository on GitHub":
    - "//github.com/midhubalan/gen-ai-4-business"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# External navigation links
nav_external_links:
  - title: Pitt Canvas
    url: https://canvas.pitt.edu/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
  - title: Vertex AI Docs 
    url: https://cloud.google.com/vertex-ai/generative-ai/docs/overview 
    hide_icon: false 
    opens_in_new_tab: true 
